name: forest-cabin
version: 0.1.0.0
license: MIT
author: Garmelon <joscha@plugh.de>
copyright: 2020 Garmelon

synopsis: A forest server hosted at forest.plugh.de
description: Please see the README at <https://github.com/Garmelon/forest#readme>
github: Garmelon/forest

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - forest-common
  - forest-server
  - microlens
  - microlens-th
  - optparse-applicative
  - stm
  - websockets

library:
  source-dirs: src

executables:
  forest-cabin:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - forest-cabin
