name: forest-common
version: 0.1.0.0
license: MIT
author: Garmelon <joscha@plugh.de>
copyright: 2020 Garmelon

synopsis: A tree-based multi-user interaction thing
description: Please see the README at <https://github.com/Garmelon/forest#readme>
github: Garmelon/forest

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - async
  - containers
  - safe
  - text
  - websockets

library:
  source-dirs: src
